### PR TITLE
Fixed zip file handling

### PR DESCRIPTION
**Pull request by SagsMug**
Makes sure zips are extracted correctly (prevent double folder)

### CODE REVIEW

**Comment by SagsMug** [comment]
we should really switch to crc32 for zip files though, since it way faster than md5

**Comment by SagsMug** [comment]
Yeah, i dont know how to isolate commits, so uri path fix comes here instead

**Comment by SagsMug** [comment]
Okay, that uri fix destroys any hope of ever loading the game for people with many songs, so, removed.

**Comment by xyonico** [comment]
Hey, could you update this to the new version I just pushed to master? And please stick to the code formatting the project already has.

**Comment by SagsMug** [comment]
Okay, this time it closed when trying to update the fork, i will just make a new pull thats ready to be accepted immediately.

**Pull request closed without merging**
